#!/bin/bash
#SBATCH --job-name=gnn
#SBATCH --ntasks=1
#SBATCH --time=48:00:00
#SBATCH --mem=32G
#SBATCH --gres=gpu:32gb:1
#SBATCH --partition=main

export PYTHONUNBUFFERED=1
module load cuda/10.2
module load anaconda
conda activate gc
python simple_node_3_2.py