#!/bin/bash
#SBATCH --job-name=malkin
#SBATCH --ntasks=1
#SBATCH --time=12:00:00
#SBATCH --mem=16G
#SBATCH --gres=gpu:32gb:1
#SBATCH --partition=main

export PYTHONUNBUFFERED=1
module load cuda/10.2
module load anaconda
conda activate gc
python malkin_2_1_10K.py