#!/bin/bash
#SBATCH --job-name=test
#SBATCH --ntasks=1
#SBATCH --time=0:01:00
#SBATCH --mem=48G
#SBATCH --gres=gpu:32gb:1
#SBATCH --partition=main

module load cuda/10.2
module load anaconda
conda activate gc
python malkin_2_1_10K.py