#!/bin/bash
#SBATCH --job-name=local_FULL
#SBATCH --ntasks=1
#SBATCH --time=48:00:00
#SBATCH --mem=16G
#SBATCH --gres=gpu:32gb:1
#SBATCH --partition=main

export PYTHONUNBUFFERED=1
module load cuda/10.2
module load anaconda
conda activate gc
python local_2_1_FULL.py